import type { Metadata } from "next";
import { Press_Start_2P } from "next/font/google";
import Header from "@/components/header";
import "./globals.css";

const getPress2Sart2P = Press_Start_2P({
  variable: "--font-press-2-start",
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${getPress2Sart2P.className} antialiased border-2 h-fit border-green-700`}
      >
        <div className="bg-yellow-700 border border-black min-h-screen pt-4 *:bg-red-500 flex flex-row justify-center ">
          {/* <Header /> */}
          {children}
        </div>
      </body>
    </html>
  );
}
